version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pretty-ms"
      - dependency-name: "p-queue"
      - dependency-name: "ora"
      - dependency-name: "chalk"
      - dependency-name: " @inquirer/prompts"